const std = @import("std");
const token = @import("token.zig");

pub const Dialect = enum {
    postgres,
    sqlserver,
    sqlite,
};

pub const Features = struct {
    top: bool,
    limit: bool,
    returning: bool,
    apply: bool,
};

pub const core_keywords = std.StaticStringMap(token.Tag).initComptime(.{
    .{ "with", .kw_with },
    .{ "select", .kw_select },
    .{ "distinct", .kw_distinct },
    .{ "from", .kw_from },
    .{ "where", .kw_where },
    .{ "group", .kw_group },
    .{ "by", .kw_by },
    .{ "order", .kw_order },
    .{ "having", .kw_having },
    .{ "between", .kw_between },
    .{ "and", .kw_and_ },
    .{ "or", .kw_or_ },
    .{ "is", .kw_is },
    .{ "in", .kw_in },
    .{ "not", .kw_not },
    .{ "like", .kw_like },
    .{ "all", .kw_all },
    .{ "exists", .kw_exists },
    .{ "any", .kw_any },
    .{ "some", .kw_some },
    .{ "insert", .kw_insert },
    .{ "update", .kw_update },
    .{ "delete", .kw_delete },
    .{ "create", .kw_create },
    .{ "alter", .kw_alter },
    .{ "drop", .kw_drop },
    .{ "cast", .kw_cast },
    .{ "as", .kw_as },
    .{ "case", .kw_case },
    .{ "when", .kw_when },
    .{ "then", .kw_then },
    .{ "else", .kw_else },
    .{ "end", .kw_end },
    .{ "asc", .kw_asc },
    .{ "desc", .kw_desc },
    .{ "over", .kw_over },
    .{ "partition", .kw_partition },
    .{ "range", .kw_range },
    .{ "offset", .kw_offset },
    .{ "fetch", .kw_fetch },
    .{ "row", .kw_row },
    .{ "rows", .kw_rows },
    .{ "first", .kw_first },
    .{ "next", .kw_next },
    .{ "only", .kw_only },
    .{ "percent", .kw_percent },
    .{ "ties", .kw_ties },
    .{ "full", .kw_full },
    .{ "left", .kw_left },
    .{ "right", .kw_right },
    .{ "inner", .kw_inner },
    .{ "outer", .kw_outer },
    .{ "join", .kw_join },
    .{ "on", .kw_on },
    .{ "following", .kw_following },
    .{ "preceding", .kw_preceding },
    .{ "unbounded", .kw_unbounded },
    .{ "current", .kw_current },
    .{ "int", .kw_int },
    .{ "bigint", .kw_bigint },
    .{ "tinyint", .kw_tinyint },
    .{ "smallint", .kw_smallint },
    .{ "bit", .kw_bit },
    .{ "float", .kw_float },
    .{ "real", .kw_real },
    .{ "date", .kw_date },
    .{ "time", .kw_time },
    .{ "decimal", .kw_decimal },
    .{ "numeric", .kw_numeric },
    .{ "varchar", .kw_varchar },
    .{ "null", .kw_null },
    .{ "true", .kw_true },
    .{ "false", .kw_false },
});

pub const postgres_keywords = std.StaticStringMap(token.Tag).initComptime(.{
    .{ "returning", .kw_returning },
    .{ "lateral", .kw_lateral },
    .{ "recursive", .kw_recursive },
    .{ "ilike", .kw_ilike },
    .{ "similar", .kw_similar },
    .{ "text", .kw_text },
    .{ "uuid", .kw_uuid },
    .{ "json", .kw_json },
    .{ "jsonb", .kw_jsonb },
    .{ "serial", .kw_serial },
    .{ "bigserial", .kw_bigserial },
    .{ "enum", .kw_enum },
});

pub const sqlite_keywords = std.StaticStringMap(token.Tag).initComptime(.{
    .{ "blob", .kw_blob },
    .{ "integer", .kw_integer },
    .{ "text", .kw_text },
    .{ "datetime", .kw_datetime },
    .{ "replace", .kw_replace },
    .{ "conflict", .kw_conflict },
    .{ "abort", .kw_abort },
    .{ "fail", .kw_fail },
    .{ "ignore", .kw_ignore },
    .{ "restrict", .kw_restrict },
    .{ "without", .kw_without },
});

pub const sqlserver_keywords = std.StaticStringMap(token.Tag).initComptime(.{
    .{ "exec", .kw_exec },
    .{ "top", .kw_top },
    .{ "declare", .kw_declare },
    .{ "set", .kw_set },
    .{ "percent", .kw_percent },
    .{ "ties", .kw_ties },
    .{ "bit", .kw_bit },
    .{ "datetime", .kw_datetime },
});
