const std = @import("std");
pub const Location = struct { line: usize, column: usize };
pub const Span = struct { start: Location, end: Location };
pub const Token = struct {
    tag: Tag,
    lexeme: []const u8,
    start_pos: Span,
    end_pos: Span,
};

pub const Tag = enum {
    identifier,
    quoted_identifier,
    local_variable,
    string_literal,
    number_literal,
    comment_line,

    illegal,
    eof,

    sharp,
    mod,
    period,
    semicolon,
    left_paren,
    right_paren,
    plus,
    minus,
    comma,
    less_than,
    greater_than,
    less_than_equal,
    greater_than_equal,
    equal,
    not_equal_bang,
    not_equal_arrow,
    plus_equal,
    minus_equal,
    multiply_equal,
    divide_equal,
    mod_equal,
    caret_equal,
    pipe_equal,
    pipe,
    ampersand_equal,
    ampersand,
    asterisk,
    forward_slash,
    tilde,

    // Keywords
    kw_with,
    kw_exec,
    kw_select,
    kw_distinct,
    kw_top,
    kw_from,
    kw_where,
    kw_insert,
    kw_update,
    kw_delete,
    kw_create,
    kw_alter,
    kw_drop,
    kw_declare,
    kw_set,
    kw_cast,
    kw_as,
    kw_asc,
    kw_desc,
    kw_and_,
    kw_or_,
    kw_order,
    kw_by,
    kw_over,
    kw_partition,
    kw_range,
    kw_offset,
    kw_fetch,
    kw_row,
    kw_rows,
    kw_first,
    kw_next,
    kw_only,
    kw_percent,
    kw_ties,
    kw_full,
    kw_left,
    kw_right,
    kw_inner,
    kw_outer,
    kw_join,
    kw_on,
    kw_having,
    kw_between,
    kw_following,
    kw_preceding,
    kw_unbounded,
    kw_current,
    kw_not,
    kw_like,
    kw_all,
    kw_exists,
    kw_any,
    kw_in,
    kw_some,
    kw_int,
    kw_bigint,
    kw_tinyint,
    kw_smallint,
    kw_bit,
    kw_float,
    kw_real,
    kw_date,
    kw_datetime,
    kw_time,
    kw_decimal,
    kw_numeric,
    kw_varchar,

    pub fn toString(tag: Tag) []const u8 {
        return switch (tag) {
            .identifier => "identifier",
            .quoted_identifier => "quoted_identifier",
            .local_variable => "local_variable",
            .string_literal => "string_literal",
            .number_literal => "number_literal",
            .comment_line => "comment_line",
            .illegal => "illegal",
            .eof => "eof",
            .sharp => "sharp",
            .mod => "mod",
            .period => "period",
            .semicolon => "semicolon",
            .left_paren => "left_paren",
            .right_paren => "right_paren",
            .plus => "plus",
            .minus => "minus",
            .comma => "comma",
            .less_than => "less_than",
            .greater_than => "greater_than",
            .less_than_equal => "less_than_equal",
            .greater_than_equal => "greater_than_equal",
            .equal => "equal",
            .not_equal_bang => "not_equal_bang",
            .not_equal_arrow => "not_equal_arrow",
            .plus_equal => "plus_equal",
            .minus_equal => "minus_equal",
            .multiply_equal => "multiply_equal",
            .divide_equal => "divide_equal",
            .mod_equal => "mod_equal",
            .caret_equal => "caret_equal",
            .pipe_equal => "pipe_equal",
            .pipe => "pipe",
            .ampersand_equal => "ampersand_equal",
            .ampersand => "ampersand",
            .asterisk => "asterisk",
            .forward_slash => "forward_slash",
            .tilde => "tilde",
            .kw_with => "kw_with",
            .kw_exec => "kw_exec",
            .kw_select => "kw_select",
            .kw_distinct => "kw_distinct",
            .kw_top => "kw_top",
            .kw_from => "kw_from",
            .kw_where => "kw_where",
            .kw_insert => "kw_insert",
            .kw_update => "kw_update",
            .kw_delete => "kw_delete",
            .kw_create => "kw_create",
            .kw_alter => "kw_alter",
            .kw_drop => "kw_drop",
            .kw_declare => "kw_declare",
            .kw_set => "kw_set",
            .kw_cast => "kw_cast",
            .kw_as => "kw_as",
            .kw_asc => "kw_asc",
            .kw_desc => "kw_desc",
            .kw_and_ => "kw_and",
            .kw_or_ => "kw_or",
            .kw_order => "kw_order",
            .kw_by => "kw_by",
            .kw_over => "kw_over",
            .kw_partition => "kw_partition",
            .kw_range => "kw_range",
            .kw_offset => "kw_offset",
            .kw_fetch => "kw_fetch",
            .kw_row => "kw_row",
            .kw_rows => "kw_rows",
            .kw_first => "kw_first",
            .kw_next => "kw_next",
            .kw_only => "kw_only",
            .kw_percent => "kw_percent",
            .kw_ties => "kw_ties",
            .kw_full => "kw_full",
            .kw_left => "kw_left",
            .kw_right => "kw_right",
            .kw_inner => "kw_inner",
            .kw_outer => "kw_outer",
            .kw_join => "kw_join",
            .kw_on => "kw_on",
            .kw_having => "kw_having",
            .kw_between => "kw_between",
            .kw_following => "kw_following",
            .kw_preceding => "kw_preceding",
            .kw_unbounded => "kw_unbounded",
            .kw_current => "kw_current",
            .kw_not => "kw_not",
            .kw_like => "kw_like",
            .kw_all => "kw_all",
            .kw_exists => "kw_exists",
            .kw_any => "kw_any",
            .kw_in => "kw_in",
            .kw_some => "kw_some",
            .kw_int => "kw_int",
            .kw_bigint => "kw_bigint",
            .kw_tinyint => "kw_tinyint",
            .kw_smallint => "kw_smallint",
            .kw_bit => "kw_bit",
            .kw_float => "kw_float",
            .kw_real => "kw_real",
            .kw_date => "kw_date",
            .kw_datetime => "kw_datetime",
            .kw_time => "kw_time",
            .kw_decimal => "kw_decimal",
            .kw_numeric => "kw_numeric",
            .kw_varchar => "kw_varchar",
        };
    }
};

// keyword types
const map = std.StaticStringMap(Tag).initComptime(.{
    .{ "with", .kw_with },
    .{ "exec", .kw_exec },
    .{ "select", .kw_select },
    .{ "distinct", .kw_distinct },
    .{ "top", .kw_top },
    .{ "from", .kw_from },
    .{ "where", .kw_where },
    .{ "insert", .kw_insert },
    .{ "update", .kw_update },
    .{ "delete", .kw_delete },
    .{ "create", .kw_create },
    .{ "alter", .kw_alter },
    .{ "drop", .kw_drop },
    .{ "declare", .kw_declare },
    .{ "set", .kw_set },
    .{ "cast", .kw_cast },
    .{ "as", .kw_as },
    .{ "asc", .kw_asc },
    .{ "desc", .kw_desc },
    .{ "and", .kw_and_ },
    .{ "or", .kw_or_ },
    .{ "order", .kw_order },
    .{ "by", .kw_by },
    .{ "over", .kw_over },
    .{ "partition", .kw_partition },
    .{ "range", .kw_range },
    .{ "offset", .kw_offset },
    .{ "fetch", .kw_fetch },
    .{ "row", .kw_row },
    .{ "rows", .kw_rows },
    .{ "first", .kw_first },
    .{ "next", .kw_next },
    .{ "only", .kw_only },
    .{ "percent", .kw_percent },
    .{ "ties", .kw_ties },
    .{ "full", .kw_full },
    .{ "left", .kw_left },
    .{ "right", .kw_right },
    .{ "inner", .kw_inner },
    .{ "outer", .kw_outer },
    .{ "join", .kw_join },
    .{ "on", .kw_on },
    .{ "having", .kw_having },
    .{ "between", .kw_between },
    .{ "following", .kw_following },
    .{ "preceding", .kw_preceding },
    .{ "unbounded", .kw_unbounded },
    .{ "current", .kw_current },
    .{ "not", .kw_not },
    .{ "like", .kw_like },
    .{ "all", .kw_all },
    .{ "exists", .kw_exists },
    .{ "any", .kw_any },
    .{ "in", .kw_in },
    .{ "some", .kw_some },
    .{ "int", .kw_int },
    .{ "bigint", .kw_bigint },
    .{ "tinyint", .kw_tinyint },
    .{ "smallint", .kw_smallint },
    .{ "bit", .kw_bit },
    .{ "float", .kw_float },
    .{ "real", .kw_real },
    .{ "date", .kw_date },
    .{ "datetime", .kw_datetime },
    .{ "time", .kw_time },
    .{ "decimal", .kw_decimal },
    .{ "numeric", .kw_numeric },
    .{ "varchar", .kw_varchar },
});

pub fn keyword(ident: []const u8) ?Tag {
    var buf = [_]u8{0} ** 20;
    if (ident.len >= buf.len) {
        return null;
    }
    const lower_ident = std.ascii.lowerString(&buf, ident);

    return map.get(lower_ident);
}
